name: primitive-mind
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
